
export const TOPICS_SCIENCES: Record<string, string[]> = {
  "Mathematics": [
    "Foundations & Logic",
      "- Naive vs axiomatic set theory (ZFC, NBG, MK)",
      "- Ordinals, cardinals, continuum hypothesis, forcing",
      "- First-order logic, completeness & soundness",
      "- Gödel’s incompleteness, Tarski’s undefinability, Löb’s theorem",
      "- Model theory (saturation, o-minimality), Proof theory (Gentzen, ordinal analysis)",
      "- Non-classical logics (intuitionistic, modal, paraconsistent)",
      "- Reverse mathematics, subsystems of second-order arithmetic",
    "Number Theory",
      "- Elementary: primes, divisibility, Euclidean algorithm, continued fractions",
      "- Analytic: Riemann zeta, Dirichlet L-functions, Prime Number Theorem, Riemann Hypothesis",
      "- Algebraic: algebraic integers, class number, units (Dirichlet, Pell)",
      "- Diophantine equations (Fermat’s Last Theorem proof overview, ABC conjecture)",
      "- Additive: Goldbach, Waring, Schnirelmann density",
      "- Transcendental number theory (Lindemann-Weierstrass, Gelfond-Schneider)",
      "- p-adic numbers, local-global principles",
    "Algebra",
      "- Group theory",
        "- Finite groups (Sylow, classification of finite simple groups, Monster group)",
        "- Infinite groups (free, amenable, hyperbolic, Gromov)",
        "- Lie groups & algebras, root systems",
      "- Ring & module theory (Noetherian, Artinian, Krull dimension, homological algebra)",
      "- Field theory & Galois theory (solvable extensions, inverse Galois problem)",
      "- Commutative algebra (Grothendieck, schemes)",
      "- Noncommutative algebra (von Neumann algebras, C*-algebras)",
      "- Representation theory (characters, induced representations, modular reps)",
    "Linear & Multilinear Algebra",
      "- Finite-dimensional (Jordan form, rational canonical, SVD, Perron-Frobenius)",
      "- Infinite-dimensional operators (spectral theorem, compact operators)",
      "- Tensor algebra, exterior algebra, Clifford algebras",
    "Category Theory & Homological Algebra",
      "- Abelian categories, derived categories, triangulated categories",
      "- Topos theory, elementary toposes",
    "Geometry & Topology",
      "- Euclidean & non-Euclidean (hyperbolic, elliptic, spherical)",
      "- Projective geometry, Desargues, Pappus",
      "- Algebraic geometry",
        "- Classical (Bézout, genus, Riemann-Roch)",
        "- Modern (schemes, étale cohomology, motives)",
      "- Differential geometry",
        "- Riemannian manifolds, curvature (sectional, Ricci, scalar)",
        "- Symplectic geometry, Kähler manifolds",
        "- Contact geometry, sub-Riemannian",
      "- Topology",
        "- General topology (compactness, connectedness, Urysohn)",
        "- Algebraic topology (fundamental group, covering spaces, homology theories, homotopy groups of spheres)",
        "- Geometric topology (knot theory, 3-manifolds, Thurston geometrization)",
        "- Manifold topology (surgery, h-cobordism, exotic spheres)",
    "Analysis",
      "- Real analysis (Lebesgue integration, Lp spaces, Radon measures)",
      "- Complex analysis (Riemann surfaces, Picard theorems, modular forms)",
      "- Functional analysis (Banach algebras, C*-algebras, von Neumann)",
      "- Harmonic analysis (Fourier on groups, Littlewood-Paley, Hardy spaces)",
      "- Distribution theory, microlocal analysis",
      "- Several complex variables, CR geometry",
    "Differential Equations & Dynamical Systems",
      "- ODEs (existence/uniqueness, linear systems, Sturm-Liouville, chaos, bifurcations)",
      "- PDEs",
        "- Elliptic (Laplace, Poisson, maximum principle)",
        "- Parabolic (heat equation, Brownian motion)",
        "- Hyperbolic (wave equation, d’Alembert)",
        "- Navier-Stokes existence & smoothness (Clay Millennium Problem)",
      "- Stochastic DEs, SPDEs",
    "Probability & Statistics",
      "- Measure-theoretic probability",
      "- Stochastic processes (Markov chains, martingales, Lévy processes, Gaussian processes)",
      "- Statistics (Bayesian vs frequentist, high-dimensional, nonparametric)",
    "Discrete Mathematics",
      "- Graph theory (extremal, random graphs, expander graphs)",
      "- Combinatorics (design theory, matroids, posets)",
      "- Cryptography (RSA, lattice-based, post-quantum)",
    "Applied & Computational Math",
      "- Numerical analysis (finite elements, spectral methods, Monte Carlo)",
      "- Optimization (convex, nonconvex, integer programming)",
      "- Control theory, information theory (Shannon, algorithmic)",
      "- Mathematical physics (solitons, integrable systems, quantum groups)",
      "- Financial math (Black-Scholes, Heston, jump models)",
      "- Data science & machine learning theory (PAC learning, kernel methods, deep learning theory)"
  ],
  "Biology": [
    "Cell & Molecular Biology",
      "- Prokaryotes vs eukaryotes, organelles (mitochondria, chloroplasts, endomembrane)",
      "- Cytoskeleton (microtubules, actin, intermediate filaments, motor proteins)",
      "- Cell cycle (cyclins, CDKs, checkpoints, cancer)",
      "- DNA (replication fork, telomeres, topoisomerases)",
      "- Transcription (RNA pol I/II/III, enhancers, epigenetics: DNA methylation, histone code)",
      "- Translation (ribosome structure, genetic code degeneracy)",
      "- Signal transduction (GPCR, RTK, MAPK, JAK-STAT, NF-κB, Wnt, Hedgehog, Notch)",
      "- CRISPR systems (Cas9, Cas12, Cas13, prime editing)",
    "Genetics & Evolution",
      "- Mendelian & extensions (incomplete dominance, epistasis, pleiotropy)",
      "- Population genetics (HWE, drift, selection, mutation-selection balance)",
      "- Speciation (allopatric, sympatric, parapatric, ring species)",
      "- Phylogenomics, molecular clocks, coalescent theory",
      "- Evo-Devo (Hox genes, heterochrony, modularity)",
    "Physiology",
      "- Human systems: nervous (action potential, synapses, neurotransmitters), endocrine (hypothalamus-pituitary axes), cardiovascular, respiratory, renal, digestive, immune (innate/adaptive, MHC, T/B cells), reproductive",
      "- Plant physiology (photosynthesis C3/C4/CAM, transpiration, phytohormones: auxin, cytokinin, ABA, ethylene, gibberellin)",
      "- Comparative (hibernation, torpor, extremophiles)",
    "Ecology",
      "- Population (logistic growth, r/K selection, Allee effects)",
      "- Community (niche, competition, predation, keystone species, succession)",
      "- Ecosystem (energy flow, nutrient cycles, resilience)",
      "- Conservation (IUCN categories, SLOSS debate, rewilding)",
      "- Global change (anthropogenic biome shifts, novel ecosystems)",
    "Systematics & Taxonomy",
      "- All phyla (Porifera → Chordata) with classes and key orders",
      "- Cladistics, parsimony, maximum likelihood, Bayesian phylogenetics",
      "- Major transitions (endosymbiosis, multicellularity, land colonization)",
    "Specialized Fields",
      "- Neuroscience (connectomics, optogenetics, neural circuits)",
      "- Immunology (cancer immunotherapy, CAR-T, checkpoint inhibitors)",
      "- Microbiology & Virology (bacteriophages, viral quasispecies, emerging diseases)",
      "- Marine biology (deep sea, hydrothermal vents, coral triangle)",
      "- Paleobiology (Cambrian explosion, Ediacaran, Burgess Shale, dinosaur-bird transition)"
  ],
  "Chemistry": [
    "General & Physical Chemistry",
      "- Thermodynamics (laws, Gibbs, Helmholtz, phase diagrams, fugacity)",
      "- Kinetics (Arrhenius, transition state theory, catalysis)",
      "- Quantum chemistry (Hartree-Fock, DFT, post-HF methods)",
      "- Statistical mechanics (ensembles, partition functions, Ising model)",
    "Inorganic",
      "- Main group (boranes, silicates, phosphazenes)",
      "- Coordination (ligand field, Tanabe-Sugano, Jahn-Teller, organometallics: Grubbs, Schrock, Wilkinson)",
      "- Solid state (crystal systems, defects, band theory)",
    "Organic",
      "- Mechanisms (arrow-pushing, pericyclic: Woodward-Hoffmann, Diels-Alder)",
      "- Synthesis (retrosynthesis, protecting groups, asymmetric: Corey, Sharpless, Noyori)",
      "- Natural products (polyketides, terpenes, alkaloids, total synthesis milestones)",
      "- Polymers & materials (step-growth vs chain-growth, dendrimers, MOFs, COFs)",
    "Analytical",
      "- Spectroscopy (NMR: 2D techniques COSY/NOESY/HSQC, EPR, XPS)",
      "- Chromatography (GC-MS, LC-MS/MS, ion mobility)",
      "- Electroanalytical (cyclic voltammetry, impedance)",
    "Biochemistry",
      "- Proteins (folding: Levinthal paradox, Anfinsen, chaperones, intrinsically disordered)",
      "- Enzymes (Michaelis-Menten, allostery, ribozymes)",
      "- Metabolism (glycolysis, TCA, pentose phosphate, urea cycle, beta-oxidation, gluconeogenesis)",
      "- Photosynthesis (Z-scheme, Calvin cycle, Rubisco)",
      "- Nucleic acids (DNA repair, recombination, transposons)",
      "- Signal molecules (NO, neurotransmitters, eicosanoids)"
  ],
  "Physics": [
    "Classical Mechanics",
      "- Newtonian, Lagrangian, Hamiltonian, Hamilton-Jacobi",
      "- Chaos (Lyapunov exponents, KAM theorem)",
      "- Continuum mechanics, fluid dynamics (Navier-Stokes, turbulence)",
    "Electromagnetism & Relativity",
      "- Maxwell equations in differential & integral forms",
      "- Special relativity (Lorentz transformation, Minkowski, E=mc²)",
      "- General relativity (Einstein field equations, Schwarzschild, Kerr, FRW cosmology, gravitational waves)",
    "Thermodynamics & Statistical Mechanics",
      "- Laws, entropy, phase transitions, critical phenomena",
      "- Quantum statistical mechanics (Bose-Einstein condensation, Fermi gases)",
    "Quantum Mechanics",
      "- Wavefunctions, operators, commutators, uncertainty",
      "- Exactly solvable: harmonic oscillator, hydrogen atom, angular momentum",
      "- Approximation methods (perturbation, variational, WKB)",
      "- Quantum information (qubits, gates, Shor, Grover, quantum error correction)",
      "- Entanglement, Bell theorems, no-cloning, quantum teleportation",
    "Quantum Field Theory",
      "- Second quantization, Feynman diagrams",
      "- QED (renormalization, running couplings)",
      "- QCD (confinement, asymptotic freedom, lattice QCD)",
      "- Electroweak unification, Higgs mechanism",
      "- Beyond Standard Model (SUSY, extra dimensions, string theory basics)",
    "Condensed Matter",
      "- Crystal structures, phonons, electrons in solids",
      "- Superconductivity (BCS, high-Tc cuprates, topological SC)",
      "- Magnetism (Ising, Heisenberg, spintronics)",
      "- Topological phases (quantum Hall, topological insulators, Majorana fermions)",
    "Particle & Nuclear Physics",
      "- Standard Model particles & interactions",
      "- Neutrino oscillations, CP violation",
      "- Nuclear structure, shell model, fission/fusion",
    "Optics & Waves",
      "- Physical optics (diffraction, interference, holography)",
      "- Nonlinear optics, lasers, photonics",
      "- Plasmonics, metamaterials"
  ],
  "Astronomy & Astrophysics": [
    "Observational Techniques",
      "- Ground telescopes (VLT, Keck, ELT, GMT)",
      "- Space telescopes (Hubble, JWST, Chandra, Fermi, future: LUVOIR, HabEx)",
      "- Multi-messenger (LIGO/Virgo, IceCube neutrinos)",
    "Solar System",
      "- Planet formation (protoplanetary disks, migration)",
      "- Exoplanets detection methods & statistics (Kepler, TESS, PLATO)",
      "- Icy moons, Mars geology, asteroid mining prospects",
    "Stellar Astrophysics",
      "- Stellar structure equations, polytropes",
      "- Evolution tracks, supernovae types (Ia, II, pair-instability)",
      "- Compact objects (white dwarfs, neutron stars: pulsars, magnetars, black holes)",
    "Galactic & Extragalactic",
      "- Milky Way (central bar, spiral arms, Gaia data)",
      "- Galaxy morphology (Hubble sequence, Sersic profiles)",
      "- AGN (quasars, blazars, Seyferts), supermassive black hole demographics",
    "Cosmology",
      "- Friedmann equations, distance ladder",
      "- Inflation (slow-roll, eternal inflation)",
      "- CMB (Planck power spectrum, B-modes, reionization)",
      "- Dark matter candidates (WIMPs, axions, primordial BH)",
      "- Dark energy (Λ, quintessence, modified gravity)",
      "- Large-scale structure (BAO, voids, filaments)",
      "- Multiverse (string landscape, eternal inflation bubbles)"
  ],
  "Artificial Intelligence": [
    "1. Fundamentos Matemáticos",
    "  1.1 Álgebra Linear",
    "    - Vetores e espaços vetoriais",
    "    - Matrizes e operações matriciais",
    "    - Autovalores e autovetores",
    "    - Decomposição de matrizes (SVD, PCA)",
    "    - Produtos internos e normas",
    "  1.2 Cálculo e Otimização",
    "    - Derivadas e gradientes",
    "    - Derivadas parciais e regra da cadeia",
    "    - Gradiente descendente e variações",
    "    - Otimizadores (SGD, Adam, RMSprop, AdaGrad)",
    "    - Funções de perda e minimização",
    "  1.3 Probabilidade e Estatística",
    "    - Probabilidade condicional e teorema de Bayes",
    "    - Distribuições de probabilidade",
    "    - Esperança, variância e covariância",
    "    - Inferência estatística",
    "    - Máxima verossimilhança",
    "  1.4 Teoria da Informação",
    "    - Entropia e entropia cruzada",
    "    - Divergência de Kullback-Leibler",
    "    - Informação mútua",
    "    - Compressão de informação",
    "2. Aprendizado de Máquina Clássico",
    "  2.1 Aprendizado Supervisionado",
    "    - Regressão linear e logística",
    "    - Árvores de decisão",
    "    - Random Forests",
    "    - Support Vector Machines (SVM)",
    "    - Naive Bayes",
    "    - K-Nearest Neighbors (KNN)",
    "  2.2 Aprendizado Não Supervisionado",
    "    - K-means clustering",
    "    - Clustering hierárquico",
    "    - DBSCAN",
    "    - Análise de componentes principais (PCA)",
    "    - t-SNE e UMAP",
    "  2.3 Conceitos Fundamentais",
    "    - Overfitting e underfitting",
    "    - Viés e variância (bias-variance tradeoff)",
    "    - Validação cruzada",
    "    - Regularização (L1, L2, Elastic Net)",
    "    - Métricas de avaliação (acurácia, precisão, recall, F1, AUC-ROC)",
    "  2.4 Engenharia de Features",
    "    - Seleção de features",
    "    - Extração de features",
    "    - Normalização e padronização",
    "    - Encoding de variáveis categóricas",
    "    - Feature scaling",
    "3. Redes Neurais Profundas",
    "  3.1 Arquitetura Básica",
    "    - Perceptron e perceptron multicamadas",
    "    - Camadas densas (fully connected)",
    "    - Funções de ativação (ReLU, sigmoid, tanh, softmax)",
    "    - Forward propagation",
    "    - Backpropagation",
    "  3.2 Treinamento de Redes Neurais",
    "    - Inicialização de pesos",
    "    - Batch, mini-batch e stochastic training",
    "    - Learning rate e learning rate scheduling",
    "    - Momentum e métodos adaptativos",
    "    - Batch normalization e layer normalization",
    "  3.3 Regularização e Generalização",
    "    - Dropout",
    "    - Early stopping",
    "    - Data augmentation",
    "    - Weight decay",
    "    - Ensembles de modelos",
    "  3.4 Arquiteturas Especializadas",
    "    - Redes convolucionais (CNNs)",
    "    - Redes recorrentes (RNNs, LSTMs, GRUs)",
    "    - Redes residuais (ResNets)",
    "    - Attention mechanisms",
    "    - Transformers",
    "4. Processamento de Linguagem Natural (NLP)",
    "  4.1 Representação de Texto",
    "    - Bag of Words e TF-IDF",
    "    - Word embeddings (Word2Vec, GloVe)",
    "    - Contextual embeddings",
    "    - Tokenização e vocabulário",
    "    - Subword tokenization (BPE, WordPiece)",
    "  4.2 Modelos de Linguagem",
    "    - N-gramas",
    "    - Modelos autorregressivos",
    "    - Modelos de linguagem mascarados",
    "    - Perplexidade e avaliação",
    "    - Pré-treinamento e fine-tuning",
    "  4.3 Arquiteturas Transformer",
    "    - Self-attention e multi-head attention",
    "    - Positional encoding",
    "    - Encoder-decoder architecture",
    "    - Transformer blocks",
    "    - Scaled dot-product attention",
    "  4.4 Modelos Grandes de Linguagem (LLMs)",
    "    - Arquiteturas base (GPT, BERT, T5)",
    "    - Decoder-only vs encoder-decoder",
    "    - Scaling laws",
    "    - Context length e memory",
    "    - Prompt engineering fundamentals",
    "5. Treinamento de Modelos Grandes",
    "  5.1 Pré-treinamento",
    "    - Objetivos de pré-treinamento",
    "    - Datasets de treinamento",
    "    - Compute requirements",
    "    - Distributed training",
    "    - Mixed precision training",
    "  5.2 Fine-tuning",
    "    - Transfer learning",
    "    - Supervised fine-tuning",
    "    - Task-specific adaptation",
    "    - Few-shot e zero-shot learning",
    "    - Parameter-efficient fine-tuning (LoRA, adapters)",
    "  5.3 Alinhamento",
    "    - Reinforcement Learning from Human Feedback (RLHF)",
    "    - Proximal Policy Optimization (PPO)",
    "    - Direct Preference Optimization (DPO)",
    "    - Constitutional AI",
    "    - Red teaming e safety testing",
    "  5.4 Infraestrutura de Treinamento",
    "    - GPUs e TPUs",
    "    - Paralelização de dados e modelos",
    "    - Gradient accumulation",
    "    - Checkpointing",
    "    - Monitoramento de treinamento",
    "6. Inferência e Geração",
    "  6.1 Métodos de Decodificação",
    "    - Greedy decoding",
    "    - Beam search",
    "    - Nucleus sampling (top-p)",
    "    - Temperature sampling",
    "    - Top-k sampling",
    "  6.2 Otimização de Inferência",
    "    - Quantização (int8, int4)",
    "    - Pruning",
    "    - Knowledge distillation",
    "    - Model compression",
    "    - Caching e KV-cache",
    "  6.3 Controle de Geração",
    "    - Prompting strategies",
    "    - Chain-of-thought prompting",
    "    - Few-shot examples",
    "    - System prompts",
    "    - Constrained generation",
    "7. Embeddings e Busca Semântica",
    "  7.1 Vetorização de Conteúdo",
    "    - Sentence embeddings"
  ]
};
