
export const TOPICS_HUMANITIES: Record<string, string[]> = {
  "History of Humanity": [
    // Pré-história e evolução humana
    "Hominin Evolution",
      "- Sahelanthropus tchadensis (7–6 Ma)",
      "- Orrorin tugenensis",
      "- Ardipithecus kadabba & ramidus",
      "- Australopithecus anamensis, afarensis (Lucy), africanus, garhi, sediba",
      "- Paranthropus aethiopicus, boisei, robustus",
      "- Homo habilis, rudolfensis, ergaster, erectus, antecessor, heidelbergensis, naledi, floresiensis",
      "- Denisovans, Neanderthals (Shanidar, Kebara, Vindija genome), Homo sapiens arcaico",
      "- Interbreeding events (1–6% Neanderthal DNA in non-Africans)",
    "Theories of Modern Human Origins",
      "- Out of Africa (Recent African Origin)",
      "- Multiregional Hypothesis",
      "- Assimilation Model",
      "- “Weak Garden of Eden” hypothesis",
    "Paleolithic",
      "- Lower Paleolithic (Oldowan, Acheulean, Movius Line)",
      "- Middle Paleolithic (Mousterian, Levallois technique, Neanderthal burials)",
      "- Upper Paleolithic (Aurignacian, Gravettian, Solutrean, Magdalenian)",
      "- Blade technology, Atlatl, Bow and arrow origins",
    "Symbolic Behavior & Art",
      "- Blombos Cave engravings (77 kya)",
      "- Chauvet, Lascaux, Altamira, Cueva de las Manos",
      "- Venus figurines (Willendorf, Dolní Věstonice, Hohle Fels)",
      "- Lion-man of Hohlenstein-Stadel, Ivory carvings",
    "Neolithic Revolution",
      "- Pre-Pottery Neolithic A/B (PPNA/PPNB)",
      "- Natufian culture, Göbekli Tepe (world’s first temple?)",
      "- Jericho (world’s oldest walled city), Çatalhöyük, ‘Ain Ghazal",
      "- Domestication syndromes (wheat, barley, rice, maize, potato, lentils, goats, sheep, cattle, pigs, dogs)",
      "- Secondary Products Revolution (milk, wool, traction)",
    "Spread of Agriculture",
      "- Fertile Crescent → Europe (LBK culture, Cardial Ware)",
      "- Indus Valley (Mehrgarh), Yellow River (Yangshao, Longshan)",
      "- Mesoamerica (Tehuacán Valley, maize domestication)",
      "- Andes (guitarero cave, quinoa, potato)",
      "- Sahel (pearl millet), New Guinea (taro, banana)",
    "Metallurgy Ages",
      "- Chalcolithic (Copper Age: Varna, Los Millares, Ötzi’s axe)",
      "- Bronze Age (Early, Middle, Late)",
        "- Bronze Age Collapse (Sea Peoples, 1177 BCE theories)",
        "- Urnfield culture, Terramare, Tumulus culture",
      "- Iron Age (Hallstatt, La Tène, Jōmon–Yayoi transition)",

    // Civilizações antigas
    "Mesopotamia (detailed chronology)",
      "- Ubaid → Uruk period (world’s first cities, proto-cuneiform)",
      "- Jemdet Nasr, Early Dynastic (city-states, Royal Tombs of Ur)",
      "- Akkadian Empire (Sargon, Naram-Sin stele)",
      "- Gutian interlude, Ur III (Shulgi bureaucracy)",
      "- Old Babylonian (Hammurabi Code), Kassites",
      "- Middle & Neo-Assyrian Empire (Ashurnasirpal II, Library of Ashurbanipal)",
      "- Neo-Babylonian (Nebuchadnezzar II, Ishtar Gate)",
    "Ancient Egypt (full periods)",
      "- Predynastic (Naqada I–III, Palette of Narmer)",
      "- Early Dynastic (Menes, Step pyramids)",
      "- Old Kingdom (Djoser, Sneferu, Great Pyramids, Sphinx)",
      "- First Intermediate Period",
      "- Middle Kingdom (Mentuhotep II, Senusret III, Fayum irrigation)",
      "- Second Intermediate (Hyksos, horse & chariot)",
      "- New Kingdom (Ahmose, Hatshepsut, Akhenaten & Amarna, Tutankhamun, Ramesses II–III, Sea Peoples)",
      "- Third Intermediate (Libyan, Kushite dynasties)",
      "- Late Period (Saite renaissance, Persian conquest)",
      "- Ptolemaic Egypt (Rosetta Stone, Library of Alexandria)",
    "Indus Valley Civilization",
      "- Mature Harappan phase (2700–1900 BCE)",
      "- Urban planning (Mohenjo-Daro grid, Great Bath, granaries)",
      "- Undeciphered script, Standardization of weights",
      "- Decline theories (climate change, Aryan migration, Sarasvati river drying)",
    "Ancient China (full dynastic cycle)",
      "- Xia (possibly Erlitou culture)",
      "- Shang (Anyang, oracle bones, bronze ritual vessels)",
      "- Zhou Dynasty",
        "- Western Zhou (Mandate of Heaven)",
        "- Eastern Zhou → Spring & Autumn + Warring States",
        "- Hundred Schools of Thought (Confucius, Laozi, Mozi, Legalists, Sun Tzu)",
      "- Qin (First Emperor, Terracotta Army, Great Wall beginnings, standardization)",
      "- Han (Silk Road, paper, seismograph, civil-service exams)",
      "- Three Kingdoms, Jin, Northern & Southern Dynasties, Sui, Tang (Golden Age), Song (economic revolution), Yuan (Kublai Khan), Ming (Zheng He, Forbidden City), Qing (Manchu conquest)",
    "Mesoamerica & Andes",
      "- Olmec (colossal heads, San Lorenzo, La Venta)",
      "- Zapotec (Monte Albán), Teotihuacan (Pyramid of the Sun, Avenue of the Dead)",
      "- Maya (Preclassic, Classic collapse, Postclassic: Chichen Itzá, Mayapan)",
      "- Toltec, Aztec (Tenochtitlan, Triple Alliance, human sacrifice cosmology)",
      "- Inca (Cuzco, Machu Picchu, road system, quipu)",
      "- Norte Chico (Caral-Supe, oldest American civilization)",
      "- Chavín, Moche, Nazca, Tiwanaku, Wari",
    "Sub-Saharan Africa",
      "- Nok culture (terracotta, iron smelting 1000 BCE)",
      "- Kingdom of Kush (Meroë pyramids, Napata)",
      "- Aksum (obelisks, Ezana’s Christianization)",
      "- Garamantes (Trans-Saharan trade)",
      "- Bantu migrations",
      "- Medieval: Ghana, Mali (Mansa Musa, Timbuktu), Songhai (Askia Muhammad), Great Zimbabwe, Mutapa, Luba-Lunda, Kongo Kingdom, Benin bronzes",

    // Mundo clássico e medieval
    "Greek World",
      "- Minoan & Mycenaean",
      "- Greek Dark Ages",
      "- Archaic (colonization, hoplites, tyrants)",
      "- Classical (Persian Wars, Delian League → Athenian Empire, Peloponnesian War)",
      "- Hellenistic kingdoms (Seleucids, Ptolemies, Antigonids, Greco-Bactrian, Indo-Greek)",
    "Roman History (full timeline)",
      "- Roman Kingdom (753–509 BCE)",
      "- Republic (509–27 BCE): Punic Wars, Social War, Gracchi, Marius vs Sulla, First Triumvirate, Caesar, Second Triumvirate",
      "- Empire: Julio-Claudian, Flavian, Nervan-Antonian (Five Good Emperors), Severan, Crisis of the Third Century, Tetrarchy, Constantine, Fall of West (476), Eastern Roman/Byzantine continuity",
    "Byzantine Empire",
      "- Justinian & Theodora (Code, Hagia Sophia, Reconquista)",
      "- Arab sieges, Theme system",
      "- Iconoclasm, Macedonian Renaissance",
      "- Komnenian restoration, Fourth Crusade (1204), Palaiologan Renaissance",
    "Islamic World",
      "- Pre-Islamic Arabia, Muhammad, Rashidun Caliphate",
      "- Umayyad (Damascus, expansion to Spain & Sindh)",
      "- Abbasid Revolution (Baghdad, House of Wisdom, Translation Movement)",
      "- Fatimid, Seljuk Turks, Ayyubid (Saladin), Mamluk Sultanate",
      "- Al-Andalus (Cordoba Caliphate, Alhambra, Conviviality & Reconquista)",
      "- Persianate dynasties (Samanid, Ghaznavid, Seljuk, Safavid, Mughal)",
    "Medieval Europe",
      "- Migration Period, Merovingian & Carolingian (Charlemagne, Treaty of Verdun)",
      "- Viking Age, Magyars, Saracens",
      "- Feudalism, Manorialism, Three Orders",
      "- Investiture Controversy, Gregorian Reform",
      "- Crusades (1095–1291), Military Orders (Templars, Hospitallers)",
      "- High Middle Ages (Gothic architecture, Scholasticism: Anselm, Abelard, Aquinas)",
      "- Black Death, Great Famine, Avignon Papacy, Western Schism",
      "- Hundred Years’ War, War of the Roses",
    "East Asia Medieval",
      "- Tang cosmopolitanism, Song economic revolution (paper money, gunpowder weapons)",
      "- Mongol Empire (Genghis Khan, Pax Mongolica, Yuan China)",
      "- Ming treasure fleets (Zheng He)",
      "- Japanese Heian → Kamakura → Muromachi → Sengoku → Tokugawa shogunate",

    // Era Moderna e Contemporânea (detalhada)
    "Renaissance & Early Modern",
      "- Italian Renaissance (Florence: Medici, Michelangelo, Leonardo, Machiavelli)",
      "- Northern Renaissance (Erasmus, Dürer, Thomas More)",
      "- Scientific Renaissance (Vesalius, Copernicus, Paracelsus)",
    "Age of Exploration & Colonization",
      "- Portuguese (Prince Henry, Vasco da Gama, Treaty of Tordesillas)",
      "- Spanish conquests (Cortés, Pizarro, Magellan-Elcano circumnavigation)",
      "- Columbian Exchange, Silver trade (Potosi), Atlantic Slave Trade",
    "Reformation & Wars of Religion",
      "- Luther’s 95 Theses, Diet of Worms",
      "- Calvinism, Zwingli, Anabaptists",
      "- English Reformation (Henry VIII, Elizabeth I)",
      "- Counter-Reformation (Jesuits, Council of Trent, Baroque art)",
      "- Thirty Years’ War → Peace of Westphalia (1648)",
    "Absolutism vs Constitutionalism",
      "- Louis XIV (Versailles, revocation of Edict of Nantes)",
      "- Peter the Great (Westernization, St Petersburg)",
      "- English Civil War, Commonwealth, Glorious Revolution (1688), Bill of Rights",
    "Enlightenment & Revolutions",
      "- Scottish Enlightenment (Hume, Smith)",
      "- French philosophes (Voltaire, Rousseau, Diderot’s Encyclopédie)",
      "- American Revolution, Declaration of Independence",
      "- French Revolution (Estates-General → Terror → Napoleon)",
      "- Haitian Revolution (Toussaint Louverture)",
      "- Latin American independence (Bolívar, San Martín, Hidalgo)",
    "Industrial Revolution",
      "- 1st (1760–1840): textile, steam, iron",
      "- 2nd (1870–1914): electricity, steel, chemicals, internal combustion",
      "- 3rd (1960s–): digital, automation",
      "- 4th (current): AI, IoT, biotech",
    "Imperialism & 19th Century",
      "- Scramble for Africa (Berlin Conference 1884–85)",
      "- Opium Wars, Unequal treaties, Meiji Restoration",
      "- Indian Rebellion 1857 → British Raj",
      "- Boer Wars, Suez Canal",
    "20th Century Wars",
      "- World War I (causes, trenches, Russian Revolution, Versailles, League of Nations)",
      "- Interwar (Great Depression, Rise of Totalitarianism: Mussolini, Hitler, Stalin, Franco)",
      "- World War II (Axis vs Allies, Holocaust, Atomic bomb, UN founding)",
      "- Cold War (Truman Doctrine → Fall of USSR 1991)",
      "- Decolonization waves (India 1947, Africa 1960, Algeria 1962)",
      "- Post-Cold War conflicts (Gulf War, Yugoslavia, 9/11, Iraq, Afghanistan, Arab Spring, Ukraine 2014/2022)",

    "Contemporary Global Issues",
      "- Globalization & Anti-globalization",
      "- Digital Revolution (Internet, Web1/2/3, AI revolution)",
      "- Climate Change & Anthropocene",
      "- Pandemics (1918 flu, HIV/AIDS, COVID-19)",
      "- Space Age & Colonization prospects"
  ],
  "Geography": [
    "Physical Geography",
      "- Geomorphology",
        "- Tectonics (subduction zones, mid-ocean ridges, transform faults, Wilson cycle)",
        "- Landforms (karst, glacial, periglacial, coastal, aeolian dunes, fluvial)",
        "- Volcanology (shield, stratovolcano, calderas, supervolcanoes)",
      "- Climatology",
        "- Atmospheric circulation (Hadley, Ferrel, Polar cells)",
        "- ENSO, MJO, IOD, NAO, monsoons",
        "- Paleoclimatology (ice cores, speleothems, Milankovitch, Dansgaard-Oeschger)",
      "- Hydrology & Oceanography",
        "- Thermohaline circulation (AMOC), upwelling zones",
        "- Ocean acidification, gyres, marine heatwaves",
      "- Biogeography",
        "- Biomes, ecoregions, biodiversity hotspots",
        "- Island biogeography, latitudinal diversity gradient",
    "Human Geography",
      "- Population (demographic transition, population pyramids, migration theories: Ravenstein, Lee, Zelinsky)",
      "- Urban (rank-size rule, megacities, suburbanization, gentrification, smart cities)",
      "- Economic (location theory: von Thünen, Weber, Christaller, Lösch; world-systems: Wallerstein)",
      "- Cultural (language families, religion diffusion, cultural hearth)",
      "- Political (state formation, boundaries, gerrymandering, supranationalism: EU, ASEAN)",
      "- Geopolitics (Mackinder Heartland, Spykman Rimland, Mahan sea power, critical geopolitics)",
    "Regional Geography",
      "- All continents + detailed subregions",
        "- Africa: Maghreb, Sahel, Horn, Great Lakes, Southern Africa, etc.",
        "- Asia: Middle East, Central Asia, South Asia, Southeast Asia, East Asia",
        "- Americas: Anglo-America, Latin America (Mesoamerica, Caribbean, Andean, Southern Cone)",
        "- Europe: Western, Eastern, Nordic, Mediterranean, Balkan",
        "- Oceania & Polar regions",
    "Resource & Environmental Geography",
      "- Energy transition, critical minerals (lithium triangle, rare earths China dominance)",
      "- Water conflicts (Nile, Jordan, Mekong)",
      "- Arctic geopolitics (Northern Sea Route, Svalbard treaty)",
    "Techniques",
      "- Cartography history & modern (projections, datums)",
      "- Remote sensing (multispectral, hyperspectral, SAR)",
      "- GIScience (spatial analysis, geostatistics, network analysis)",
      "- GNSS (GPS, Galileo, BeiDou), LiDAR, drone mapping"
  ],
  "Philosophy": [
    "Ancient",
      "- Pre-Socratics (Thales → Anaxagoras → Atomists)",
      "- Sophists, Socrates, Plato (Forms, cave allegory, dialogues)",
      "- Aristotle (logic, physics, metaphysics, ethics, politics)",
      "- Hellenistic schools (Stoics, Epicureans, Skeptics, Cynics)",
    "Medieval",
      "- Patristic (Augustine, confession, predestination)",
      "- Islamic (Al-Kindi, Al-Farabi, Avicenna, Averroes, Al-Ghazali)",
      "- Jewish (Maimonides)",
      "- Scholastic (Anselm ontological argument, Aquinas Five Ways, Scotus, Ockham’s razor)",
    "Early Modern",
      "- Rationalism (Descartes, Spinoza, Leibniz)",
      "- Empiricism (Locke, Berkeley, Hume)",
      "- Kant (transcendental idealism, categorical imperative)",
      "- German Idealism (Fichte, Schelling, Hegel, Schopenhauer)",
      "- Utilitarianism (Bentham, Mill), Marx (dialectical materialism)",
      "- Nietzsche (will to power, eternal recurrence, Übermensch)",
    "20th-21st Century",
      "- Analytic: Frege, Russell, early Wittgenstein, logical positivism (Vienna Circle), ordinary language (later Wittgenstein, Austin), Quine, Kripke (rigid designators), Davidson",
      "- Continental: Phenomenology (Husserl, Heidegger Being and Time), Existentialism (Sartre, Camus), Critical Theory (Frankfurt School), Structuralism (Lévi-Strauss, Saussure), Post-structuralism (Foucault, Derrida, Deleuze & Guattari)",
    "Branches",
      "- Epistemology (foundationalism, coherentism, reliabilism, virtue epistemology)",
      "- Metaphysics (realism vs anti-realism, free will, personal identity)",
      "- Ethics (metaethics: moral realism/cognitivism, normative theories, applied: bioethics, AI ethics)",
      "- Philosophy of Science (Popper falsification, Kuhn paradigms, Lakatos research programmes)",
      "- Philosophy of Mind (dualism, physicalism, functionalism, panpsychism)",
      "- Aesthetics, Political Philosophy (Rawls, Nozick, communitarianism)"
  ],
  "Literature": [
    "I. FUNDAMENTOS TEÓRICOS E CONCEITUAIS",
    "- 1. Conceitos e Natureza da Literatura",
    "  - 1.1. O que é literatura",
    "  - 1.2. Funções da literatura: estética, social, moral, política, simbólica",
    "  - 1.3. Literatura x linguagem comum",
    "  - 1.4. Ficção, verossimilhança e representação",
    "  - 1.5. Arte da palavra e poder simbólico",
    "- 2. Estrutura Literária",
    "  - 2.1. Enredo, narrador, personagens, tempo e espaço",
    "  - 2.2. Ritmo, métrica, sonoridade e forma",
    "  - 2.3. Gêneros literários:",
    "    - Lírico",
    "    - Épico",
    "    - Dramático",
    "    - Narrativo",
    "    - Ensaístico",
    "    - Epistolar",
    "    - Experimental",
    "- 3. Elementos Estilísticos",
    "  - 3.1. Figuras de linguagem e tropologia",
    "  - 3.2. Estilo individual e estilo de época",
    "  - 3.3. Linguagem simbólica e alegoria",
    "  - 3.4. Ironia, paródia e metalinguagem",
    "- 4. Funções Sociais e Psicológicas",
    "  - 4.1. Literatura e formação cultural",
    "  - 4.2. Catarsis e experiência estética",
    "  - 4.3. Literatura como instrumento de poder",
    "  - 4.4. A função política e ideológica da ficção",

    "II. LITERATURA DA ANTIGUIDADE",
    "- 1. Literaturas do Oriente Antigo",
    "  - 1.1. Mesopotâmia: Epopeia de Gilgamesh",
    "  - 1.2. Egito: Textos das Pirâmides, Livro dos Mortos",
    "  - 1.3. Índia: Mahabharata, Ramayana, Vedas, Upanishads",
    "  - 1.4. China: I Ching, Analectos (Confúcio), Tao Te Ching (Lao-Tsé)",
    "  - 1.5. Pérsia: Avesta, poesia de Rumi e Ferdusi",
    "- 2. Literatura Hebraica e Bíblica",
    "  - 2.1. Antigo Testamento como texto literário",
    "  - 2.2. Poesia sapiencial e profética",
    "  - 2.3. Cânticos, parábolas e mitopoese",
    "- 3. Literatura Grega",
    "  - 3.1. Épica: Homero (Ilíada, Odisseia)",
    "  - 3.2. Lírica: Safo, Píndaro",
    "  - 3.3. Tragédia: Ésquilo, Sófocles, Eurípides",
    "  - 3.4. Comédia: Aristófanes",
    "  - 3.5. Filosofia como literatura: Platão, Aristóteles",
    "  - 3.6. Retórica e historiografia: Heródoto, Tucídides",
    "- 4. Literatura Romana",
    "  - 4.1. Épica: Virgílio (Eneida)",
    "  - 4.2. Lírica: Horácio, Ovídio",
    "  - 4.3. Sátira: Juvenal",
    "  - 4.4. Prosa e filosofia: Sêneca, Cícero, Tácito",
    "  - 4.5. Teatro e oratória romana",

    "III. LITERATURA MEDIEVAL (SÉC. V–XV)",
    "- 1. Características Gerais",
    "  - 1.1. Teocentrismo e moral religiosa",
    "  - 1.2. Transmissão oral e manuscrita",
    "  - 1.3. Alegoria e simbolismo",
    "- 2. Literatura Cristã e Clerical",
    "  - 2.1. Hagiografias e sermões",
    "  - 2.2. Mistérios, milagres e moralidades",
    "  - 2.3. A literatura dos mosteiros",
    "- 3. Literatura Popular e Cavalheiresca",
    "  - 3.1. Cantares de gesta (Rolando, El Cid)",
    "  - 3.2. Ciclo Arturiano e Tristão e Isolda",
    "  - 3.3. Romances corteses e trovadorescos",
    "- 4. Trovadorismo",
    "  - 4.1. Cantigas de amor, amigo e escárnio",
    "  - 4.2. Poesia provençal",
    "  - 4.3. O trovadorismo ibérico",
    "- 5. Outras Literaturas Medievais",
    "  - 5.1. Poesia árabe e persa",
    "  - 5.2. Literatura nórdica e sagas islandesas",
    "  - 5.3. Mil e Uma Noites e narrativa oriental",

    "IV. RENASCIMENTO (SÉC. XIV–XVI)",
    "- 1. Humanismo e Antropocentrismo",
    "- 2. Redescoberta dos Clássicos",
    "- 3. Principais Autores e Obras",
    "  - Itália: Dante, Petrarca, Boccaccio",
    "  - Portugal: Camões",
    "  - Espanha: Garcilaso, Cervantes",
    "  - Inglaterra: Shakespeare, Marlowe",
    "  - França: Rabelais, Montaigne",
    "- 4. Teatro e Filosofia Renascentista",
    "- 5. Literatura de viagens e descobrimentos",

    "V. CLASSICISMO E BARROCO",
    "- 1. Classicismo",
    "  - 1.1. Ideal de medida e razão",
    "  - 1.2. Influência de Aristóteles e Horácio",
    "  - 1.3. Poesia de perfeição formal (Camões, Tasso)",
    "- 2. Barroco",
    "  - 2.1. Contraste e antítese: corpo x alma",
    "  - 2.2. Temas da fugacidade e da morte",
    "  - 2.3. Autores: Gôngora, Quevedo, Donne, Gregório de Matos",

    "VI. ILUSTRAÇÃO E NEOCLASSICISMO (SÉC. XVIII)",
    "- 1. O Século das Luzes",
    "  - 1.1. Racionalismo e crítica social",
    "  - 1.2. Enciclopédia e difusão do saber",
    "  - 1.3. Literatura filosófica: Voltaire, Rousseau, Diderot",
    "  - 1.4. Teatro ilustrado: Beaumarchais",
    "  - 1.5. Poesia moral: Pope, Bocage",

    "VII. ROMANTISMO (SÉC. XIX)",
    "- 1. Contexto histórico e ideológico",
    "  - 1.1. Revoluções e nacionalismos",
    "  - 1.2. Subjetividade e natureza",
    "  - 1.3. O gênio criador",
    "- 2. Correntes Regionais",
    "  - 2.1. Romantismo inglês: Byron, Shelley, Keats",
    "  - 2.2. Alemão: Goethe, Schiller, Novalis",
    "  - 2.3. Francês: Hugo, Musset, Lamartine",
    "  - 2.4. Russo: Púchkin, Lérmontov",
    "  - 2.5. Brasileiro e latino-americano: Alencar, Castro Alves",
    "- 3. Temas e Formas",
    "  - 3.1. Liberdade formal",
    "  - 3.2. O amor idealizado e o exílio",
    "  - 3.3. O herói marginal",

    "VIII. REALISMO, NATURALISMO E PARNASIANISMO",
    "- 1. Realismo",
    "  - 1.1. Crítica à idealização romântica",
    "  - 1.2. Estilo objetivo e analítico",
    "  - 1.3. Autores: Flaubert, Machado de Assis, Tolstói",
    "- 2. Naturalismo",
    "  - 2.1. Determinismo biológico e social",
    "  - 2.2. Zola e o romance experimental",
    "  - 2.3. Temas de miséria e vício",
    "- 3. Parnasianismo e objetividade estética",

    "IX. SIMBOLISMO E MODERNIDADE",
    "- 1. Esteticismo e musicalidade",
    "- 2. Autores: Baudelaire, Verlaine, Mallarmé, Cruz e Sousa",
    "- 3. Transição para o Modernismo",

    "X. VANGUARDAS E MODERNISMO (SÉC. XX)",
    "- 1. Vanguardas Europeias",
    "  - Futurismo",
    "  - Cubismo",
    "  - Dadaísmo",
    "  - Surrealismo",
    "  - Expressionismo",
    "  - Construtivismo",
    "- 2. Modernismo em Diversas Regiões",
    "  - Anglo-americano: Eliot, Joyce, Woolf",
    "  - Francês: Apollinaire",
    "  - Brasileiro: Oswald e Mário de Andrade",
    "  - Hispano-americano: Borges, Neruda, Vallejo",
    "- 3. Características",
    "  - Fragmentação e simultaneidade",
    "  - Ironia e anti-herói",
    "  - Rejeição da linearidade narrativa",

    "XI. LITERATURA CONTEMPORÂNEA (1945–ATUAL)",
    "- 1. Pós-modernismo e metanarrativas",
    "- 2. Realismo mágico e neofantástico (García Márquez, Cortázar, Allende)",
    "- 3. Literatura existencialista (Sartre, Camus)",
    "- 4. Teatro do absurdo (Beckett, Ionesco, Pinter)",
    "- 5. Minimalismo, autoficção e fragmento",
    "- 6. Feminismo e estudos de gênero (Woolf, Beauvoir, Atwood, Adichie)",
    "- 7. Pós-colonialismo e vozes periféricas",
    "- 8. Ecocrítica e literatura ambiental",
    "- 9. Ficção científica e distopia (Orwell, Huxley, Dick, Le Guin)",
    "- 10. Literatura global e multiculturalismo",

    "XII. LITERATURA DIGITAL E HÍBRIDA",
    "- 1. Hipertexto e narrativa interativa",
    "- 2. Literatura de plataforma e redes sociais",
    "- 3. Poesia digital, bots e IA criativa",
    "- 4. Escrita colaborativa e fanfiction",
    "- 5. Realidade aumentada e ficção imersiva",

    "XIII. LITERATURA COMPARADA E INTERDISCIPLINAR",
    "- 1. Literatura e filosofia",
    "- 2. Literatura e psicologia (Freud, Jung, Lacan)",
    "- 3. Literatura e sociologia",
    "- 4. Literatura e cinema",
    "- 5. Literatura e música",
    "- 6. Literatura e artes visuais",
    "- 7. Mitologia comparada e arquétipos",

    "XIV. TEORIA LITERÁRIA E CRÍTICA",
    "- 1. Formalismo russo",
    "- 2. Estruturalismo e semiótica (Saussure, Barthes)",
    "- 3. Pós-estruturalismo (Derrida, Foucault)",
    "- 4. Hermenêutica (Gadamer, Ricoeur)",
    "- 5. Crítica marxista e cultural (Lukács, Eagleton)",
    "- 6. Estudos de gênero e queer",
    "- 7. Estudos pós-coloniais (Said, Spivak, Bhabha)",
    "- 8. Teoria da recepção (Iser, Jauss)",
    "- 9. Narratologia e discurso",

    "XV. LITERATURAS REGIONAIS E NACIONAIS (MACROZONAS)",
    "- 1. Europa Ocidental",
    "  - França, Inglaterra, Alemanha, Itália, Espanha, Portugal",
    "- 2. Europa Oriental",
    "  - Rússia, Polônia, Tchecoslováquia, Hungria, Bálcãs",
    "- 3. América do Norte",
    "  - EUA, Canadá, México",
    "- 4. América Latina",
    "  - Brasil, Argentina, Chile, Colômbia, Peru, Cuba",
    "- 5. África",
    "  - Literatura subsaariana e pós-colonial",
    "  - Autores: Achebe, Soyinka, Coetzee",
    "- 6. Ásia",
    "  - China, Japão, Índia, Irã, Oriente Médio",
    "- 7. Oceania",
    "  - Austrália, Nova Zelândia, Ilhas do Pacífico",
    "- 8. Lusofonia mundial",
    "  - Portugal, Brasil, Angola, Moçambique, Cabo Verde",

    "XVI. TENDÊNCIAS FUTURAS",
    "- 1. Ciborgues literários e autoria híbrida",
    "- 2. Ética e propriedade intelectual na era da IA",
    "- 3. Literatura transnacional e nômade",
    "- 4. Arquivos digitais e preservação da memória literária",
    "- 5. A fusão entre humano, máquina e narrativa",
  ]
};
