import type { LanguageOption, AnalysisTopic, StyleGuideOption } from './types';

// Otimização de Cota: Reduzido para 1.
// Artigos longos consomem muitos tokens. 1 iteração é o equilíbrio ideal para contas gratuitas.
export const TOTAL_ITERATIONS = 1;

export const LANGUAGES: LanguageOption[] = [
    { code: 'en', name: 'English', flag: '🇬🇧' },
    { code: 'pt', name: 'Português', flag: '🇧🇷' },
    { code: 'es', name: 'Español', flag: '🇪🇸' },
    { code: 'fr', name: 'Français', flag: '🇫🇷' },
];

export const AVAILABLE_MODELS: {name: string, description: string}[] = [
    { name: 'gemini-flash-lite-latest', description: 'Google: Very fast, for simple tasks & high volume.' },
    { name: 'gemini-2.5-flash', description: 'Google: Fast and efficient for most tasks.' },
    { name: 'gemini-3-pro-preview', description: 'Google: Most powerful for complex generation and reasoning.' },
    { name: 'grok-4-latest', description: 'x.ai: Powerful alternative model.' },
];

export const STYLE_GUIDES: StyleGuideOption[] = [
    { key: 'abnt', name: 'ABNT', description: 'Associação Brasileira de Normas Técnicas NBR 6023' },
    { key: 'apa', name: 'APA', description: 'American Psychological Association 7th Edition' },
    { key: 'mla', name: 'MLA', description: 'Modern Language Association 9th Edition' },
    { key: 'ieee', name: 'IEEE', description: 'Institute of Electrical and Electronics Engineers' },
];

export const ANALYSIS_TOPICS: AnalysisTopic[] = [
    { num: 0, name: 'TOPIC FOCUS', desc: 'Mantém o foco central sem desviar.' },
    { num: 1, name: 'WRITING CLARITY', desc: 'Qualidade gramatical e legibilidade.' },
    { num: 2, name: 'METHODOLOGICAL RIGOR', desc: 'Validez científica da metodologia.' },
    { num: 3, name: 'ORIGINALITY', desc: 'Contribuição nova para a área.' },
    { num: 4, name: 'LITERATURE REVIEW', desc: 'Uso adequado de fontes e contexto.' },
    { num: 5, name: 'METHODOLOGY CLARITY', desc: 'Clareza e reprodutibilidade.' },
    { num: 6, name: 'RESULTS PRESENTATION', desc: 'Organização e objetividade dos resultados.' },
    { num: 7, name: 'DISCUSSION DEPTH', desc: 'Interpretação e link com teoria.' },
    { num: 8, 'name': 'ABSTRACT QUALITY', desc: 'Resumo conciso e completo.' },
    { num: 9, name: 'INTRODUCTION QUALITY', desc: 'Contexto e definição do problema.' },
    { num: 10, name: 'CONCLUSION QUALITY', desc: 'Resumo de achados e trabalhos futuros.' },
    { num: 11, name: 'ARGUMENTATION STRENGTH', desc: 'Lógica e evidências.' },
    { num: 12, name: 'COHERENCE AND FLOW', desc: 'Transições suaves entre seções.' },
    { num: 13, name: 'STRUCTURE', desc: 'Organização geral do LaTeX.' },
    { num: 14, name: 'REFERENCES', desc: 'Formatação e relevância.' },
    { num: 17, name: 'TITLE-CONTENT ALIGNMENT', desc: 'Alinhamento entre título e conteúdo.' },
    { num: 28, name: 'PAGE COUNT', desc: 'Adesão ao tamanho solicitado.' }
];

export const FIX_OPTIONS: { key: string; label: string; description: string }[] = [
    {
        key: 'escape_chars',
        label: 'Fix Character Escaping',
        description: 'Scans the document for special LaTeX characters (like %, $, _, &) that were not correctly escaped and fixes them.'
    },
    {
        key: 'citation_mismatch',
        label: 'Fix Citation Mismatches',
        description: 'Ensures that every \\cite{...} command in the text has a corresponding \\bibitem entry in the bibliography, and vice-versa.'
    },
    {
        key: 'preamble_check',
        label: 'Verify Preamble',
        description: 'Checks if the document preamble uses only the allowed packages in the correct order as specified by the generation rules.'
    }
];

export const DISCIPLINE_AUTHORS: Record<string, string> = {
    "Mathematics": "MATH, 10",
    "History of Humanity": "HISTORY, 10",
    "Geography": "GEOGRAPHY, 10",
    "Biology": "BIOLOGY, 10",
    "Chemistry": "CHEMISTRY, 10",
    "Physics": "PHYSICS, 10",
    "Astronomy & Astrophysics": "ASTRO, 10",
    "Philosophy": "PHILOSOPHY, 10",
    "Literature": "LITERATURE, 10"
};

export const ALL_TOPICS_BY_DISCIPLINE: Record<string, string[]> = {
  "History of Humanity": [
    // Pré-história e evolução humana
    "Hominin Evolution",
      "- Sahelanthropus tchadensis (7–6 Ma)",
      "- Orrorin tugenensis",
      "- Ardipithecus kadabba & ramidus",
      "- Australopithecus anamensis, afarensis (Lucy), africanus, garhi, sediba",
      "- Paranthropus aethiopicus, boisei, robustus",
      "- Homo habilis, rudolfensis, ergaster, erectus, antecessor, heidelbergensis, naledi, floresiensis",
      "- Denisovans, Neanderthals (Shanidar, Kebara, Vindija genome), Homo sapiens arcaico",
      "- Interbreeding events (1–6% Neanderthal DNA in non-Africans)",
    "Theories of Modern Human Origins",
      "- Out of Africa (Recent African Origin)",
      "- Multiregional Hypothesis",
      "- Assimilation Model",
      "- “Weak Garden of Eden” hypothesis",
    "Paleolithic",
      "- Lower Paleolithic (Oldowan, Acheulean, Movius Line)",
      "- Middle Paleolithic (Mousterian, Levallois technique, Neanderthal burials)",
      "- Upper Paleolithic (Aurignacian, Gravettian, Solutrean, Magdalenian)",
      "- Blade technology, Atlatl, Bow and arrow origins",
    "Symbolic Behavior & Art",
      "- Blombos Cave engravings (77 kya)",
      "- Chauvet, Lascaux, Altamira, Cueva de las Manos",
      "- Venus figurines (Willendorf, Dolní Věstonice, Hohle Fels)",
      "- Lion-man of Hohlenstein-Stadel, Ivory carvings",
    "Neolithic Revolution",
      "- Pre-Pottery Neolithic A/B (PPNA/PPNB)",
      "- Natufian culture, Göbekli Tepe (world’s first temple?)",
      "- Jericho (world’s oldest walled city), Çatalhöyük, ‘Ain Ghazal",
      "- Domestication syndromes (wheat, barley, rice, maize, potato, lentils, goats, sheep, cattle, pigs, dogs)",
      "- Secondary Products Revolution (milk, wool, traction)",
    "Spread of Agriculture",
      "- Fertile Crescent → Europe (LBK culture, Cardial Ware)",
      "- Indus Valley (Mehrgarh), Yellow River (Yangshao, Longshan)",
      "- Mesoamerica (Tehuacán Valley, maize domestication)",
      "- Andes (guitarero cave, quinoa, potato)",
      "- Sahel (pearl millet), New Guinea (taro, banana)",
    "Metallurgy Ages",
      "- Chalcolithic (Copper Age: Varna, Los Millares, Ötzi’s axe)",
      "- Bronze Age (Early, Middle, Late)",
        "- Bronze Age Collapse (Sea Peoples, 1177 BCE theories)",
        "- Urnfield culture, Terramare, Tumulus culture",
      "- Iron Age (Hallstatt, La Tène, Jōmon–Yayoi transition)",

    // Civilizações antigas
    "Mesopotamia (detailed chronology)",
      "- Ubaid → Uruk period (world’s first cities, proto-cuneiform)",
      "- Jemdet Nasr, Early Dynastic (city-states, Royal Tombs of Ur)",
      "- Akkadian Empire (Sargon, Naram-Sin stele)",
      "- Gutian interlude, Ur III (Shulgi bureaucracy)",
      "- Old Babylonian (Hammurabi Code), Kassites",
      "- Middle & Neo-Assyrian Empire (Ashurnasirpal II, Library of Ashurbanipal)",
      "- Neo-Babylonian (Nebuchadnezzar II, Ishtar Gate)",
    "Ancient Egypt (full periods)",
      "- Predynastic (Naqada I–III, Palette of Narmer)",
      "- Early Dynastic (Menes, Step pyramids)",
      "- Old Kingdom (Djoser, Sneferu, Great Pyramids, Sphinx)",
      "- First Intermediate Period",
      "- Middle Kingdom (Mentuhotep II, Senusret III, Fayum irrigation)",
      "- Second Intermediate (Hyksos, horse & chariot)",
      "- New Kingdom (Ahmose, Hatshepsut, Akhenaten & Amarna, Tutankhamun, Ramesses II–III, Sea Peoples)",
      "- Third Intermediate (Libyan, Kushite dynasties)",
      "- Late Period (Saite renaissance, Persian conquest)",
      "- Ptolemaic Egypt (Rosetta Stone, Library of Alexandria)",
    "Indus Valley Civilization",
      "- Mature Harappan phase (2700–1900 BCE)",
      "- Urban planning (Mohenjo-Daro grid, Great Bath, granaries)",
      "- Undeciphered script, Standardization of weights",
      "- Decline theories (climate change, Aryan migration, Sarasvati river drying)",
    "Ancient China (full dynastic cycle)",
      "- Xia (possibly Erlitou culture)",
      "- Shang (Anyang, oracle bones, bronze ritual vessels)",
      "- Zhou Dynasty",
        "- Western Zhou (Mandate of Heaven)",
        "- Eastern Zhou → Spring & Autumn + Warring States",
        "- Hundred Schools of Thought (Confucius, Laozi, Mozi, Legalists, Sun Tzu)",
      "- Qin (First Emperor, Terracotta Army, Great Wall beginnings, standardization)",
      "- Han (Silk Road, paper, seismograph, civil-service exams)",
      "- Three Kingdoms, Jin, Northern & Southern Dynasties, Sui, Tang (Golden Age), Song (economic revolution), Yuan (Kublai Khan), Ming (Zheng He, Forbidden City), Qing (Manchu conquest)",
    "Mesoamerica & Andes",
      "- Olmec (colossal heads, San Lorenzo, La Venta)",
      "- Zapotec (Monte Albán), Teotihuacan (Pyramid of the Sun, Avenue of the Dead)",
      "- Maya (Preclassic, Classic collapse, Postclassic: Chichen Itzá, Mayapan)",
      "- Toltec, Aztec (Tenochtitlan, Triple Alliance, human sacrifice cosmology)",
      "- Inca (Cuzco, Machu Picchu, road system, quipu)",
      "- Norte Chico (Caral-Supe, oldest American civilization)",
      "- Chavín, Moche, Nazca, Tiwanaku, Wari",
    "Sub-Saharan Africa",
      "- Nok culture (terracotta, iron smelting 1000 BCE)",
      "- Kingdom of Kush (Meroë pyramids, Napata)",
      "- Aksum (obelisks, Ezana’s Christianization)",
      "- Garamantes (Trans-Saharan trade)",
      "- Bantu migrations",
      "- Medieval: Ghana, Mali (Mansa Musa, Timbuktu), Songhai (Askia Muhammad), Great Zimbabwe, Mutapa, Luba-Lunda, Kongo Kingdom, Benin bronzes",

    // Mundo clássico e medieval
    "Greek World",
      "- Minoan & Mycenaean",
      "- Greek Dark Ages",
      "- Archaic (colonization, hoplites, tyrants)",
      "- Classical (Persian Wars, Delian League → Athenian Empire, Peloponnesian War)",
      "- Hellenistic kingdoms (Seleucids, Ptolemies, Antigonids, Greco-Bactrian, Indo-Greek)",
    "Roman History (full timeline)",
      "- Roman Kingdom (753–509 BCE)",
      "- Republic (509–27 BCE): Punic Wars, Social War, Gracchi, Marius vs Sulla, First Triumvirate, Caesar, Second Triumvirate",
      "- Empire: Julio-Claudian, Flavian, Nervan-Antonian (Five Good Emperors), Severan, Crisis of the Third Century, Tetrarchy, Constantine, Fall of West (476), Eastern Roman/Byzantine continuity",
    "Byzantine Empire",
      "- Justinian & Theodora (Code, Hagia Sophia, Reconquista)",
      "- Arab sieges, Theme system",
      "- Iconoclasm, Macedonian Renaissance",
      "- Komnenian restoration, Fourth Crusade (1204), Palaiologan Renaissance",
    "Islamic World",
      "- Pre-Islamic Arabia, Muhammad, Rashidun Caliphate",
      "- Umayyad (Damascus, expansion to Spain & Sindh)",
      "- Abbasid Revolution (Baghdad, House of Wisdom, Translation Movement)",
      "- Fatimid, Seljuk Turks, Ayyubid (Saladin), Mamluk Sultanate",
      "- Al-Andalus (Cordoba Caliphate, Alhambra, Conviviality & Reconquista)",
      "- Persianate dynasties (Samanid, Ghaznavid, Seljuk, Safavid, Mughal)",
    "Medieval Europe",
      "- Migration Period, Merovingian & Carolingian (Charlemagne, Treaty of Verdun)",
      "- Viking Age, Magyars, Saracens",
      "- Feudalism, Manorialism, Three Orders",
      "- Investiture Controversy, Gregorian Reform",
      "- Crusades (1095–1291), Military Orders (Templars, Hospitallers)",
      "- High Middle Ages (Gothic architecture, Scholasticism: Anselm, Abelard, Aquinas)",
      "- Black Death, Great Famine, Avignon Papacy, Western Schism",
      "- Hundred Years’ War, War of the Roses",
    "East Asia Medieval",
      "- Tang cosmopolitanism, Song economic revolution (paper money, gunpowder weapons)",
      "- Mongol Empire (Genghis Khan, Pax Mongolica, Yuan China)",
      "- Ming treasure fleets (Zheng He)",
      "- Japanese Heian → Kamakura → Muromachi → Sengoku → Tokugawa shogunate",

    // Era Moderna e Contemporânea (detalhada)
    "Renaissance & Early Modern",
      "- Italian Renaissance (Florence: Medici, Michelangelo, Leonardo, Machiavelli)",
      "- Northern Renaissance (Erasmus, Dürer, Thomas More)",
      "- Scientific Renaissance (Vesalius, Copernicus, Paracelsus)",
    "Age of Exploration & Colonization",
      "- Portuguese (Prince Henry, Vasco da Gama, Treaty of Tordesillas)",
      "- Spanish conquests (Cortés, Pizarro, Magellan-Elcano circumnavigation)",
      "- Columbian Exchange, Silver trade (Potosi), Atlantic Slave Trade",
    "Reformation & Wars of Religion",
      "- Luther’s 95 Theses, Diet of Worms",
      "- Calvinism, Zwingli, Anabaptists",
      "- English Reformation (Henry VIII, Elizabeth I)",
      "- Counter-Reformation (Jesuits, Council of Trent, Baroque art)",
      "- Thirty Years’ War → Peace of Westphalia (1648)",
    "Absolutism vs Constitutionalism",
      "- Louis XIV (Versailles, revocation of Edict of Nantes)",
      "- Peter the Great (Westernization, St Petersburg)",
      "- English Civil War, Commonwealth, Glorious Revolution (1688), Bill of Rights",
    "Enlightenment & Revolutions",
      "- Scottish Enlightenment (Hume, Smith)",
      "- French philosophes (Voltaire, Rousseau, Diderot’s Encyclopédie)",
      "- American Revolution, Declaration of Independence",
      "- French Revolution (Estates-General → Terror → Napoleon)",
      "- Haitian Revolution (Toussaint Louverture)",
      "- Latin American independence (Bolívar, San Martín, Hidalgo)",
    "Industrial Revolution",
      "- 1st (1760–1840): textile, steam, iron",
      "- 2nd (1870–1914): electricity, steel, chemicals, internal combustion",
      "- 3rd (1960s–): digital, automation",
      "- 4th (current): AI, IoT, biotech",
    "Imperialism & 19th Century",
      "- Scramble for Africa (Berlin Conference 1884–85)",
      "- Opium Wars, Unequal treaties, Meiji Restoration",
      "- Indian Rebellion 1857 → British Raj",
      "- Boer Wars, Suez Canal",
    "20th Century Wars",
      "- World War I (causes, trenches, Russian Revolution, Versailles, League of Nations)",
      "- Interwar (Great Depression, Rise of Totalitarianism: Mussolini, Hitler, Stalin, Franco)",
      "- World War II (Axis vs Allies, Holocaust, Atomic bomb, UN founding)",
      "- Cold War (Truman Doctrine → Fall of USSR 1991)",
      "- Decolonization waves (India 1947, Africa 1960, Algeria 1962)",
      "- Post-Cold War conflicts (Gulf War, Yugoslavia, 9/11, Iraq, Afghanistan, Arab Spring, Ukraine 2014/2022)",

    "Contemporary Global Issues",
      "- Globalization & Anti-globalization",
      "- Digital Revolution (Internet, Web1/2/3, AI revolution)",
      "- Climate Change & Anthropocene",
      "- Pandemics (1918 flu, HIV/AIDS, COVID-19)",
      "- Space Age & Colonization prospects"
  ],

  "Mathematics": [
    "Foundations & Logic",
      "- Naive vs axiomatic set theory (ZFC, NBG, MK)",
      "- Ordinals, cardinals, continuum hypothesis, forcing",
      "- First-order logic, completeness & soundness",
      "- Gödel’s incompleteness, Tarski’s undefinability, Löb’s theorem",
      "- Model theory (saturation, o-minimality), Proof theory (Gentzen, ordinal analysis)",
      "- Non-classical logics (intuitionistic, modal, paraconsistent)",
      "- Reverse mathematics, subsystems of second-order arithmetic",
    "Number Theory",
      "- Elementary: primes, divisibility, Euclidean algorithm, continued fractions",
      "- Analytic: Riemann zeta, Dirichlet L-functions, Prime Number Theorem, Riemann Hypothesis",
      "- Algebraic: algebraic integers, class number, units (Dirichlet, Pell)",
      "- Diophantine equations (Fermat’s Last Theorem proof overview, ABC conjecture)",
      "- Additive: Goldbach, Waring, Schnirelmann density",
      "- Transcendental number theory (Lindemann-Weierstrass, Gelfond-Schneider)",
      "- p-adic numbers, local-global principles",
    "Algebra",
      "- Group theory",
        "- Finite groups (Sylow, classification of finite simple groups, Monster group)",
        "- Infinite groups (free, amenable, hyperbolic, Gromov)",
        "- Lie groups & algebras, root systems",
      "- Ring & module theory (Noetherian, Artinian, Krull dimension, homological algebra)",
      "- Field theory & Galois theory (solvable extensions, inverse Galois problem)",
      "- Commutative algebra (Grothendieck, schemes)",
      "- Noncommutative algebra (von Neumann algebras, C*-algebras)",
      "- Representation theory (characters, induced representations, modular reps)",
    "Linear & Multilinear Algebra",
      "- Finite-dimensional (Jordan form, rational canonical, SVD, Perron-Frobenius)",
      "- Infinite-dimensional operators (spectral theorem, compact operators)",
      "- Tensor algebra, exterior algebra, Clifford algebras",
    "Category Theory & Homological Algebra",
      "- Abelian categories, derived categories, triangulated categories",
      "- Topos theory, elementary toposes",
    "Geometry & Topology",
      "- Euclidean & non-Euclidean (hyperbolic, elliptic, spherical)",
      "- Projective geometry, Desargues, Pappus",
      "- Algebraic geometry",
        "- Classical (Bézout, genus, Riemann-Roch)",
        "- Modern (schemes, étale cohomology, motives)",
      "- Differential geometry",
        "- Riemannian manifolds, curvature (sectional, Ricci, scalar)",
        "- Symplectic geometry, Kähler manifolds",
        "- Contact geometry, sub-Riemannian",
      "- Topology",
        "- General topology (compactness, connectedness, Urysohn)",
        "- Algebraic topology (fundamental group, covering spaces, homology theories, homotopy groups of spheres)",
        "- Geometric topology (knot theory, 3-manifolds, Thurston geometrization)",
        "- Manifold topology (surgery, h-cobordism, exotic spheres)",
    "Analysis",
      "- Real analysis (Lebesgue integration, Lp spaces, Radon measures)",
      "- Complex analysis (Riemann surfaces, Picard theorems, modular forms)",
      "- Functional analysis (Banach algebras, C*-algebras, von Neumann)",
      "- Harmonic analysis (Fourier on groups, Littlewood-Paley, Hardy spaces)",
      "- Distribution theory, microlocal analysis",
      "- Several complex variables, CR geometry",
    "Differential Equations & Dynamical Systems",
      "- ODEs (existence/uniqueness, linear systems, Sturm-Liouville, chaos, bifurcations)",
      "- PDEs",
        "- Elliptic (Laplace, Poisson, maximum principle)",
        "- Parabolic (heat equation, Brownian motion)",
        "- Hyperbolic (wave equation, d’Alembert)",
        "- Navier-Stokes existence & smoothness (Clay Millennium Problem)",
      "- Stochastic DEs, SPDEs",
    "Probability & Statistics",
      "- Measure-theoretic probability",
      "- Stochastic processes (Markov chains, martingales, Lévy processes, Gaussian processes)",
      "- Statistics (Bayesian vs frequentist, high-dimensional, nonparametric)",
    "Discrete Mathematics",
      "- Graph theory (extremal, random graphs, expander graphs)",
      "- Combinatorics (design theory, matroids, posets)",
      "- Cryptography (RSA, lattice-based, post-quantum)",
    "Applied & Computational Math",
      "- Numerical analysis (finite elements, spectral methods, Monte Carlo)",
      "- Optimization (convex, nonconvex, integer programming)",
      "- Control theory, information theory (Shannon, algorithmic)",
      "- Mathematical physics (solitons, integrable systems, quantum groups)",
      "- Financial math (Black-Scholes, Heston, jump models)",
      "- Data science & machine learning theory (PAC learning, kernel methods, deep learning theory)"
  ],

  "Geography": [
    "Physical Geography",
      "- Geomorphology",
        "- Tectonics (subduction zones, mid-ocean ridges, transform faults, Wilson cycle)",
        "- Landforms (karst, glacial, periglacial, coastal, aeolian dunes, fluvial)",
        "- Volcanology (shield, stratovolcano, calderas, supervolcanoes)",
      "- Climatology",
        "- Atmospheric circulation (Hadley, Ferrel, Polar cells)",
        "- ENSO, MJO, IOD, NAO, monsoons",
        "- Paleoclimatology (ice cores, speleothems, Milankovitch, Dansgaard-Oeschger)",
      "- Hydrology & Oceanography",
        "- Thermohaline circulation (AMOC), upwelling zones",
        "- Ocean acidification, gyres, marine heatwaves",
      "- Biogeography",
        "- Biomes, ecoregions, biodiversity hotspots",
        "- Island biogeography, latitudinal diversity gradient",
    "Human Geography",
      "- Population (demographic transition, population pyramids, migration theories: Ravenstein, Lee, Zelinsky)",
      "- Urban (rank-size rule, megacities, suburbanization, gentrification, smart cities)",
      "- Economic (location theory: von Thünen, Weber, Christaller, Lösch; world-systems: Wallerstein)",
      "- Cultural (language families, religion diffusion, cultural hearth)",
      "- Political (state formation, boundaries, gerrymandering, supranationalism: EU, ASEAN)",
      "- Geopolitics (Mackinder Heartland, Spykman Rimland, Mahan sea power, critical geopolitics)",
    "Regional Geography",
      "- All continents + detailed subregions",
        "- Africa: Maghreb, Sahel, Horn, Great Lakes, Southern Africa, etc.",
        "- Asia: Middle East, Central Asia, South Asia, Southeast Asia, East Asia",
        "- Americas: Anglo-America, Latin America (Mesoamerica, Caribbean, Andean, Southern Cone)",
        "- Europe: Western, Eastern, Nordic, Mediterranean, Balkan",
        "- Oceania & Polar regions",
    "Resource & Environmental Geography",
      "- Energy transition, critical minerals (lithium triangle, rare earths China dominance)",
      "- Water conflicts (Nile, Jordan, Mekong)",
      "- Arctic geopolitics (Northern Sea Route, Svalbard treaty)",
    "Techniques",
      "- Cartography history & modern (projections, datums)",
      "- Remote sensing (multispectral, hyperspectral, SAR)",
      "- GIScience (spatial analysis, geostatistics, network analysis)",
      "- GNSS (GPS, Galileo, BeiDou), LiDAR, drone mapping"
  ],

  "Biology": [
    "Cell & Molecular Biology",
      "- Prokaryotes vs eukaryotes, organelles (mitochondria, chloroplasts, endomembrane)",
      "- Cytoskeleton (microtubules, actin, intermediate filaments, motor proteins)",
      "- Cell cycle (cyclins, CDKs, checkpoints, cancer)",
      "- DNA (replication fork, telomeres, topoisomerases)",
      "- Transcription (RNA pol I/II/III, enhancers, epigenetics: DNA methylation, histone code)",
      "- Translation (ribosome structure, genetic code degeneracy)",
      "- Signal transduction (GPCR, RTK, MAPK, JAK-STAT, NF-κB, Wnt, Hedgehog, Notch)",
      "- CRISPR systems (Cas9, Cas12, Cas13, prime editing)",
    "Genetics & Evolution",
      "- Mendelian & extensions (incomplete dominance, epistasis, pleiotropy)",
      "- Population genetics (HWE, drift, selection, mutation-selection balance)",
      "- Speciation (allopatric, sympatric, parapatric, ring species)",
      "- Phylogenomics, molecular clocks, coalescent theory",
      "- Evo-Devo (Hox genes, heterochrony, modularity)",
    "Physiology",
      "- Human systems: nervous (action potential, synapses, neurotransmitters), endocrine (hypothalamus-pituitary axes), cardiovascular, respiratory, renal, digestive, immune (innate/adaptive, MHC, T/B cells), reproductive",
      "- Plant physiology (photosynthesis C3/C4/CAM, transpiration, phytohormones: auxin, cytokinin, ABA, ethylene, gibberellin)",
      "- Comparative (hibernation, torpor, extremophiles)",
    "Ecology",
      "- Population (logistic growth, r/K selection, Allee effects)",
      "- Community (niche, competition, predation, keystone species, succession)",
      "- Ecosystem (energy flow, nutrient cycles, resilience)",
      "- Conservation (IUCN categories, SLOSS debate, rewilding)",
      "- Global change (anthropogenic biome shifts, novel ecosystems)",
    "Systematics & Taxonomy",
      "- All phyla (Porifera → Chordata) with classes and key orders",
      "- Cladistics, parsimony, maximum likelihood, Bayesian phylogenetics",
      "- Major transitions (endosymbiosis, multicellularity, land colonization)",
    "Specialized Fields",
      "- Neuroscience (connectomics, optogenetics, neural circuits)",
      "- Immunology (cancer immunotherapy, CAR-T, checkpoint inhibitors)",
      "- Microbiology & Virology (bacteriophages, viral quasispecies, emerging diseases)",
      "- Marine biology (deep sea, hydrothermal vents, coral triangle)",
      "- Paleobiology (Cambrian explosion, Ediacaran, Burgess Shale, dinosaur-bird transition)"
  ],

  "Chemistry": [
    "General & Physical Chemistry",
      "- Thermodynamics (laws, Gibbs, Helmholtz, phase diagrams, fugacity)",
      "- Kinetics (Arrhenius, transition state theory, catalysis)",
      "- Quantum chemistry (Hartree-Fock, DFT, post-HF methods)",
      "- Statistical mechanics (ensembles, partition functions, Ising model)",
    "Inorganic",
      "- Main group (boranes, silicates, phosphazenes)",
      "- Coordination (ligand field, Tanabe-Sugano, Jahn-Teller, organometallics: Grubbs, Schrock, Wilkinson)",
      "- Solid state (crystal systems, defects, band theory)",
    "Organic",
      "- Mechanisms (arrow-pushing, pericyclic: Woodward-Hoffmann, Diels-Alder)",
      "- Synthesis (retrosynthesis, protecting groups, asymmetric: Corey, Sharpless, Noyori)",
      "- Natural products (polyketides, terpenes, alkaloids, total synthesis milestones)",
      "- Polymers & materials (step-growth vs chain-growth, dendrimers, MOFs, COFs)",
    "Analytical",
      "- Spectroscopy (NMR: 2D techniques COSY/NOESY/HSQC, EPR, XPS)",
      "- Chromatography (GC-MS, LC-MS/MS, ion mobility)",
      "- Electroanalytical (cyclic voltammetry, impedance)",
    "Biochemistry",
      "- Proteins (folding: Levinthal paradox, Anfinsen, chaperones, intrinsically disordered)",
      "- Enzymes (Michaelis-Menten, allostery, ribozymes)",
      "- Metabolism (glycolysis, TCA, pentose phosphate, urea cycle, beta-oxidation, gluconeogenesis)",
      "- Photosynthesis (Z-scheme, Calvin cycle, Rubisco)",
      "- Nucleic acids (DNA repair, recombination, transposons)",
      "- Signal molecules (NO, neurotransmitters, eicosanoids)"
  ],

  "Physics": [
    "Classical Mechanics",
      "- Newtonian, Lagrangian, Hamiltonian, Hamilton-Jacobi",
      "- Chaos (Lyapunov exponents, KAM theorem)",
      "- Continuum mechanics, fluid dynamics (Navier-Stokes, turbulence)",
    "Electromagnetism & Relativity",
      "- Maxwell equations in differential & integral forms",
      "- Special relativity (Lorentz transformation, Minkowski, E=mc²)",
      "- General relativity (Einstein field equations, Schwarzschild, Kerr, FRW cosmology, gravitational waves)",
    "Thermodynamics & Statistical Mechanics",
      "- Laws, entropy, phase transitions, critical phenomena",
      "- Quantum statistical mechanics (Bose-Einstein condensation, Fermi gases)",
    "Quantum Mechanics",
      "- Wavefunctions, operators, commutators, uncertainty",
      "- Exactly solvable: harmonic oscillator, hydrogen atom, angular momentum",
      "- Approximation methods (perturbation, variational, WKB)",
      "- Quantum information (qubits, gates, Shor, Grover, quantum error correction)",
      "- Entanglement, Bell theorems, no-cloning, quantum teleportation",
    "Quantum Field Theory",
      "- Second quantization, Feynman diagrams",
      "- QED (renormalization, running couplings)",
      "- QCD (confinement, asymptotic freedom, lattice QCD)",
      "- Electroweak unification, Higgs mechanism",
      "- Beyond Standard Model (SUSY, extra dimensions, string theory basics)",
    "Condensed Matter",
      "- Crystal structures, phonons, electrons in solids",
      "- Superconductivity (BCS, high-Tc cuprates, topological SC)",
      "- Magnetism (Ising, Heisenberg, spintronics)",
      "- Topological phases (quantum Hall, topological insulators, Majorana fermions)",
    "Particle & Nuclear Physics",
      "- Standard Model particles & interactions",
      "- Neutrino oscillations, CP violation",
      "- Nuclear structure, shell model, fission/fusion",
    "Optics & Waves",
      "- Physical optics (diffraction, interference, holography)",
      "- Nonlinear optics, lasers, photonics",
      "- Plasmonics, metamaterials"
  ],

  "Astronomy & Astrophysics": [
    "Observational Techniques",
      "- Ground telescopes (VLT, Keck, ELT, GMT)",
      "- Space telescopes (Hubble, JWST, Chandra, Fermi, future: LUVOIR, HabEx)",
      "- Multi-messenger (LIGO/Virgo, IceCube neutrinos)",
    "Solar System",
      "- Planet formation (protoplanetary disks, migration)",
      "- Exoplanets detection methods & statistics (Kepler, TESS, PLATO)",
      "- Icy moons, Mars geology, asteroid mining prospects",
    "Stellar Astrophysics",
      "- Stellar structure equations, polytropes",
      "- Evolution tracks, supernovae types (Ia, II, pair-instability)",
      "- Compact objects (white dwarfs, neutron stars: pulsars, magnetars, black holes)",
    "Galactic & Extragalactic",
      "- Milky Way (central bar, spiral arms, Gaia data)",
      "- Galaxy morphology (Hubble sequence, Sersic profiles)",
      "- AGN (quasars, blazars, Seyferts), supermassive black hole demographics",
    "Cosmology",
      "- Friedmann equations, distance ladder",
      "- Inflation (slow-roll, eternal inflation)",
      "- CMB (Planck power spectrum, B-modes, reionization)",
      "- Dark matter candidates (WIMPs, axions, primordial BH)",
      "- Dark energy (Λ, quintessence, modified gravity)",
      "- Large-scale structure (BAO, voids, filaments)",
      "- Multiverse (string landscape, eternal inflation bubbles)"
  ],

  "Philosophy": [
    "Ancient",
      "- Pre-Socratics (Thales → Anaxagoras → Atomists)",
      "- Sophists, Socrates, Plato (Forms, cave allegory, dialogues)",
      "- Aristotle (logic, physics, metaphysics, ethics, politics)",
      "- Hellenistic schools (Stoics, Epicureans, Skeptics, Cynics)",
    "Medieval",
      "- Patristic (Augustine, confession, predestination)",
      "- Islamic (Al-Kindi, Al-Farabi, Avicenna, Averroes, Al-Ghazali)",
      "- Jewish (Maimonides)",
      "- Scholastic (Anselm ontological argument, Aquinas Five Ways, Scotus, Ockham’s razor)",
    "Early Modern",
      "- Rationalism (Descartes, Spinoza, Leibniz)",
      "- Empiricism (Locke, Berkeley, Hume)",
      "- Kant (transcendental idealism, categorical imperative)",
      "- German Idealism (Fichte, Schelling, Hegel, Schopenhauer)",
      "- Utilitarianism (Bentham, Mill), Marx (dialectical materialism)",
      "- Nietzsche (will to power, eternal recurrence, Übermensch)",
    "20th-21st Century",
      "- Analytic: Frege, Russell, early Wittgenstein, logical positivism (Vienna Circle), ordinary language (later Wittgenstein, Austin), Quine, Kripke (rigid designators), Davidson",
      "- Continental: Phenomenology (Husserl, Heidegger Being and Time), Existentialism (Sartre, Camus), Critical Theory (Frankfurt School), Structuralism (Lévi-Strauss, Saussure), Post-structuralism (Foucault, Derrida, Deleuze & Guattari)",
    "Branches",
      "- Epistemology (foundationalism, coherentism, reliabilism, virtue epistemology)",
      "- Metaphysics (realism vs anti-realism, free will, personal identity)",
      "- Ethics (metaethics: moral realism/cognitivism, normative theories, applied: bioethics, AI ethics)",
      "- Philosophy of Science (Popper falsification, Kuhn paradigms, Lakatos research programmes)",
      "- Philosophy of Mind (dualism, physicalism, functionalism, panpsychism)",
      "- Aesthetics, Political Philosophy (Rawls, Nozick, communitarianism)"
  ],
  
  "Literature": [
    "I. FUNDAMENTOS TEÓRICOS E CONCEITUAIS",
    "- 1. Conceitos e Natureza da Literatura",
    "  - 1.1. O que é literatura",
    "  - 1.2. Funções da literatura: estética, social, moral, política, simbólica",
    "  - 1.3. Literatura x linguagem comum",
    "  - 1.4. Ficção, verossimilhança e representação",
    "  - 1.5. Arte da palavra e poder simbólico",
    "- 2. Estrutura Literária",
    "  - 2.1. Enredo, narrador, personagens, tempo e espaço",
    "  - 2.2. Ritmo, métrica, sonoridade e forma",
    "  - 2.3. Gêneros literários:",
    "    - Lírico",
    "    - Épico",
    "    - Dramático",
    "    - Narrativo",
    "    - Ensaístico",
    "    - Epistolar",
    "    - Experimental",
    "- 3. Elementos Estilísticos",
    "  - 3.1. Figuras de linguagem e tropologia",
    "  - 3.2. Estilo individual e estilo de época",
    "  - 3.3. Linguagem simbólica e alegoria",
    "  - 3.4. Ironia, paródia e metalinguagem",
    "- 4. Funções Sociais e Psicológicas",
    "  - 4.1. Literatura e formação cultural",
    "  - 4.2. Catarsis e experiência estética",
    "  - 4.3. Literatura como instrumento de poder",
    "  - 4.4. A função política e ideológica da ficção",

    "II. LITERATURA DA ANTIGUIDADE",
    "- 1. Literaturas do Oriente Antigo",
    "  - 1.1. Mesopotâmia: Epopeia de Gilgamesh",
    "  - 1.2. Egito: Textos das Pirâmides, Livro dos Mortos",
    "  - 1.3. Índia: Mahabharata, Ramayana, Vedas, Upanishads",
    "  - 1.4. China: I Ching, Analectos (Confúcio), Tao Te Ching (Lao-Tsé)",
    "  - 1.5. Pérsia: Avesta, poesia de Rumi e Ferdusi",
    "- 2. Literatura Hebraica e Bíblica",
    "  - 2.1. Antigo Testamento como texto literário",
    "  - 2.2. Poesia sapiencial e profética",
    "  - 2.3. Cânticos, parábolas e mitopoese",
    "- 3. Literatura Grega",
    "  - 3.1. Épica: Homero (Ilíada, Odisseia)",
    "  - 3.2. Lírica: Safo, Píndaro",
    "  - 3.3. Tragédia: Ésquilo, Sófocles, Eurípides",
    "  - 3.4. Comédia: Aristófanes",
    "  - 3.5. Filosofia como literatura: Platão, Aristóteles",
    "  - 3.6. Retórica e historiografia: Heródoto, Tucídides",
    "- 4. Literatura Romana",
    "  - 4.1. Épica: Virgílio (Eneida)",
    "  - 4.2. Lírica: Horácio, Ovídio",
    "  - 4.3. Sátira: Juvenal",
    "  - 4.4. Prosa e filosofia: Sêneca, Cícero, Tácito",
    "  - 4.5. Teatro e oratória romana",

    "III. LITERATURA MEDIEVAL (SÉC. V–XV)",
    "- 1. Características Gerais",
    "  - 1.1. Teocentrismo e moral religiosa",
    "  - 1.2. Transmissão oral e manuscrita",
    "  - 1.3. Alegoria e simbolismo",
    "- 2. Literatura Cristã e Clerical",
    "  - 2.1. Hagiografias e sermões",
    "  - 2.2. Mistérios, milagres e moralidades",
    "  - 2.3. A literatura dos mosteiros",
    "- 3. Literatura Popular e Cavalheiresca",
    "  - 3.1. Cantares de gesta (Rolando, El Cid)",
    "  - 3.2. Ciclo Arturiano e Tristão e Isolda",
    "  - 3.3. Romances corteses e trovadorescos",
    "- 4. Trovadorismo",
    "  - 4.1. Cantigas de amor, amigo e escárnio",
    "  - 4.2. Poesia provençal",
    "  - 4.3. O trovadorismo ibérico",
    "- 5. Outras Literaturas Medievais",
    "  - 5.1. Poesia árabe e persa",
    "  - 5.2. Literatura nórdica e sagas islandesas",
    "  - 5.3. Mil e Uma Noites e narrativa oriental",

    "IV. RENASCIMENTO (SÉC. XIV–XVI)",
    "- 1. Humanismo e Antropocentrismo",
    "- 2. Redescoberta dos Clássicos",
    "- 3. Principais Autores e Obras",
    "  - Itália: Dante, Petrarca, Boccaccio",
    "  - Portugal: Camões",
    "  - Espanha: Garcilaso, Cervantes",
    "  - Inglaterra: Shakespeare, Marlowe",
    "  - França: Rabelais, Montaigne",
    "- 4. Teatro e Filosofia Renascentista",
    "- 5. Literatura de viagens e descobrimentos",

    "V. CLASSICISMO E BARROCO",
    "- 1. Classicismo",
    "  - 1.1. Ideal de medida e razão",
    "  - 1.2. Influência de Aristóteles e Horácio",
    "  - 1.3. Poesia de perfeição formal (Camões, Tasso)",
    "- 2. Barroco",
    "  - 2.1. Contraste e antítese: corpo x alma",
    "  - 2.2. Temas da fugacidade e da morte",
    "  - 2.3. Autores: Gôngora, Quevedo, Donne, Gregório de Matos",

    "VI. ILUSTRAÇÃO E NEOCLASSICISMO (SÉC. XVIII)",
    "- 1. O Século das Luzes",
    "  - 1.1. Racionalismo e crítica social",
    "  - 1.2. Enciclopédia e difusão do saber",
    "  - 1.3. Literatura filosófica: Voltaire, Rousseau, Diderot",
    "  - 1.4. Teatro ilustrado: Beaumarchais",
    "  - 1.5. Poesia moral: Pope, Bocage",

    "VII. ROMANTISMO (SÉC. XIX)",
    "- 1. Contexto histórico e ideológico",
    "  - 1.1. Revoluções e nacionalismos",
    "  - 1.2. Subjetividade e natureza",
    "  - 1.3. O gênio criador",
    "- 2. Correntes Regionais",
    "  - 2.1. Romantismo inglês: Byron, Shelley, Keats",
    "  - 2.2. Alemão: Goethe, Schiller, Novalis",
    "  - 2.3. Francês: Hugo, Musset, Lamartine",
    "  - 2.4. Russo: Púchkin, Lérmontov",
    "  - 2.5. Brasileiro e latino-americano: Alencar, Castro Alves",
    "- 3. Temas e Formas",
    "  - 3.1. Liberdade formal",
    "  - 3.2. O amor idealizado e o exílio",
    "  - 3.3. O herói marginal",

    "VIII. REALISMO, NATURALISMO E PARNASIANISMO",
    "- 1. Realismo",
    "  - 1.1. Crítica à idealização romântica",
    "  - 1.2. Estilo objetivo e analítico",
    "  - 1.3. Autores: Flaubert, Machado de Assis, Tolstói",
    "- 2. Naturalismo",
    "  - 2.1. Determinismo biológico e social",
    "  - 2.2. Zola e o romance experimental",
    "  - 2.3. Temas de miséria e vício",
    "- 3. Parnasianismo e objetividade estética",

    "IX. SIMBOLISMO E MODERNIDADE",
    "- 1. Esteticismo e musicalidade",
    "- 2. Autores: Baudelaire, Verlaine, Mallarmé, Cruz e Sousa",
    "- 3. Transição para o Modernismo",

    "X. VANGUARDAS E MODERNISMO (SÉC. XX)",
    "- 1. Vanguardas Europeias",
    "  - Futurismo",
    "  - Cubismo",
    "  - Dadaísmo",
    "  - Surrealismo",
    "  - Expressionismo",
    "  - Construtivismo",
    "- 2. Modernismo em Diversas Regiões",
    "  - Anglo-americano: Eliot, Joyce, Woolf",
    "  - Francês: Apollinaire",
    "  - Brasileiro: Oswald e Mário de Andrade",
    "  - Hispano-americano: Borges, Neruda, Vallejo",
    "- 3. Características",
    "  - Fragmentação e simultaneidade",
    "  - Ironia e anti-herói",
    "  - Rejeição da linearidade narrativa",

    "XI. LITERATURA CONTEMPORânea (1945–ATUAL)",
    "- 1. Pós-modernismo e metanarrativas",
    "- 2. Realismo mágico e neofantástico (García Márquez, Cortázar, Allende)",
    "- 3. Literatura existencialista (Sartre, Camus)",
    "- 4. Teatro do absurdo (Beckett, Ionesco, Pinter)",
    "- 5. Minimalismo, autoficção e fragmento",
    "- 6. Feminismo e estudos de gênero (Woolf, Beauvoir, Atwood, Adichie)",
    "- 7. Pós-colonialismo e vozes periféricas",
    "- 8. Ecocrítica e literatura ambiental",
    "- 9. Ficção científica e distopia (Orwell, Huxley, Dick, Le Guin)",
    "- 10. Literatura global e multiculturalismo",

    "XII. LITERATURA DIGITAL E HÍBRIDA",
    "- 1. Hipertexto e narrativa interativa",
    "- 2. Literatura de plataforma e redes sociais",
    "- 3. Poesia digital, bots e IA criativa",
    "- 4. Escrita colaborativa e fanfiction",
    "- 5. Realidade aumentada e ficção imersiva",

    "XIII. LITERATURA COMPARADA E INTERDISCIPLINAR",
    "- 1. Literatura e filosofia",
    "- 2. Literatura e psicologia (Freud, Jung, Lacan)",
    "- 3. Literatura e sociologia",
    "- 4. Literatura e cinema",
    "- 5. Literatura e música",
    "- 6. Literatura e artes visuais",
    "- 7. Mitologia comparada e arquétipos",

    "XIV. TEORIA LITERÁRIA E CRÍTICA",
    "- 1. Formalismo russo",
    "- 2. Estruturalismo e semiótica (Saussure, Barthes)",
    "- 3. Pós-estruturalismo (Derrida, Foucault)",
    "- 4. Hermenêutica (Gadamer, Ricoeur)",
    "- 5. Crítica marxista e cultural (Lukács, Eagleton)",
    "- 6. Estudos de gênero e queer",
    "- 7. Estudos pós-coloniais (Said, Spivak, Bhabha)",
    "- 8. Teoria da recepção (Iser, Jauss)",
    "- 9. Narratologia e discurso",

    "XV. LITERATURAS REGIONAIS E NACIONAIS (MACROZONAS)",
    "- 1. Europa Ocidental",
    "  - França, Inglaterra, Alemanha, Itália, Espanha, Portugal",
    "- 2. Europa Oriental",
    "  - Rússia, Polônia, Tchecoslováquia, Hungria, Bálcãs",
    "- 3. América do Norte",
    "  - EUA, Canadá, México",
    "- 4. América Latina",
    "  - Brasil, Argentina, Chile, Colômbia, Peru, Cuba",
    "- 5. África",
    "  - Literatura subsaariana e pós-colonial",
    "  - Autores: Achebe, Soyinka, Coetzee",
    "- 6. Ásia",
    "  - China, Japão, Índia, Irã, Oriente Médio",
    "- 7. Oceania",
    "  - Austrália, Nova Zelândia, Ilhas do Pacífico",
    "- 8. Lusofonia mundial",
    "  - Portugal, Brasil, Angola, Moçambique, Cabo Verde",

    "XVI. TENDÊNCIAS FUTURAS",
    "- 1. Ciborgues literários e autoria híbrida",
    "- 2. Ética e propriedade intelectual na era da IA",
    "- 3. Literatura transnacional e nômade",
    "- 4. Arquivos digitais e preservação da memória literária",
    "- 5. A fusão entre humano, máquina e narrativa",
  ]
};

/**
 * Returns a list of all available disciplines.
 * @returns {string[]} An array of discipline names.
 */
export function getAllDisciplines(): string[] {
    return Object.keys(ALL_TOPICS_BY_DISCIPLINE);
}

/**
 * Returns a random topic from a specified discipline or from all disciplines if none is specified.
 * @param {string} [discipline] - The optional discipline name to get a topic from.
 * @returns {string} A random topic string.
 */
export function getRandomTopic(discipline?: string): string {
    const disciplinesToChooseFrom = discipline ? [discipline] : Object.keys(ALL_TOPICS_BY_DISCIPLINE);
    if (disciplinesToChooseFrom.length === 0) {
        throw new Error("No disciplines available to choose a topic from.");
    }
    const selectedDiscipline = disciplinesToChooseFrom[Math.floor(Math.random() * disciplinesToChooseFrom.length)];
    const topics = ALL_TOPICS_BY_DISCIPLINE[selectedDiscipline];
    if (!topics || topics.length === 0) {
        // Fallback if the selected discipline somehow has no topics, should not happen with current data
        const fallbackDisciplines = Object.keys(ALL_TOPICS_BY_DISCIPLINE).filter(d => ALL_TOPICS_BY_DISCIPLINE[d].length > 0);
        const fallbackDiscipline = fallbackDisciplines[Math.floor(Math.random() * fallbackDisciplines.length)];
        const fallbackTopics = ALL_TOPICS_BY_DISCIPLINE[fallbackDiscipline];
        return fallbackTopics[Math.floor(Math.random() * fallbackTopics.length)];
    }
    return topics[Math.floor(Math.random() * topics.length)];
}


export const SEMANTIC_SCHOLAR_API_BASE_URL = 'https://api.semanticscholar.org/graph/v1/paper/search';